version: '3.1'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - '8080:80'   # host:guest
        depends_on:
            - db
        # wait for the database to be ready before it runs the server.js
        # https://docs.docker.com/compose/startup-order/
        command: sh -c '/server/scripts/wait-for.sh db:5432 -- npm start'
        environment:
            - DATABASE_URL=postgres://postgres:password@db:5432/postgres
            - PORT=80
