version: '3.6'

services:
  server:
    image: 354634314980.dkr.ecr.us-east-2.amazonaws.com/nba-backend-server
    restart: always
    depends_on:
      - mysql
    command: sh -c '/usr/app/scripts/wait-for.sh mysql:3306 -- npm start'
    ports:
      - 80:8080

  mysql:
    image: 354634314980.dkr.ecr.us-east-2.amazonaws.com/nba-backend-db
    restart: always
